### ISSUE TITLE
Tensorflow Install error

### ISSUE THREAD

**Issue by rsmithde** [vincentteyssier/emotion-detection-raspberry#1]
I am having issues when running this line of code
'sudo pip3 install tensorflow-1.1.0-cp34-cp34m-linux_armv7l.whl'

I get this message 'tensorflow-1.1.0... is not a supported wheel on this platform.'

I tried replacing the 34 with 35 and still no luck. Any ideas?

**Comment by vincentteyssier** [comment]
Tensorflow 1.1.0 is legacy since quite a while, please visit tensorflow website for instructions as how to install the latest version, 1.9.0

**Comment by vincentteyssier** [comment]
One more detail, raspberry pi images are now supporting tf 1.9
